package in.abc.model;
// Generated Nov 11, 2014 7:51:57 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Dept generated by hbm2java
 */
public class Dept  implements java.io.Serializable {


     private short deptNo;
     private String deptName;
     private Set<Emp> emps = new HashSet<Emp>(0);

    public Dept() {
    }

	
    public Dept(short deptNo) {
        this.deptNo = deptNo;
    }
    public Dept(short deptNo, String deptName, Set<Emp> emps) {
       this.deptNo = deptNo;
       this.deptName = deptName;
       this.emps = emps;
    }
   
    public short getDeptNo() {
        return this.deptNo;
    }
    
    public void setDeptNo(short deptNo) {
        this.deptNo = deptNo;
    }
    public String getDeptName() {
        return this.deptName;
    }
    
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }
    public Set<Emp> getEmps() {
        return this.emps;
    }
    
    public void setEmps(Set<Emp> emps) {
        this.emps = emps;
    }




}


