package in.abc.model;
// Generated Oct 16, 2014 7:36:55 AM by Hibernate Tools 3.6.0



/**
 * Emp generated by hbm2java
 */
public class Emp  implements java.io.Serializable {


     private short empNo;
     private Dept dept;
     private String empName;

    public Emp() {
    }

	
    public Emp(short empNo) {
        this.empNo = empNo;
    }
    public Emp(short empNo, Dept dept, String empName) {
       this.empNo = empNo;
       this.dept = dept;
       this.empName = empName;
    }
   
    public short getEmpNo() {
        return this.empNo;
    }
    
    public void setEmpNo(short empNo) {
        this.empNo = empNo;
    }
    public Dept getDept() {
        return this.dept;
    }
    
    public void setDept(Dept dept) {
        this.dept = dept;
    }
    public String getEmpName() {
        return this.empName;
    }
    
    public void setEmpName(String empName) {
        this.empName = empName;
    }




}


