<!DOCTYPE html>
<html>
    <head>
        <title><%=title%></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="styles/style.css"/>
    </head>
    <body>
        <div id="main">
            <div id="header">
                <h1>MVC App</h1>
            </div>
            <div id="menu">
                <a href="index.jsp">Home</a>
                <a href="category">Category</a>
                <a href="product">Product</a>
            </div>
            <div id="content">
                
            